language: node_js
node_js:
  - "5.3"
before_script:
  - openssl aes-256-cbc -K $encrypted_89b7d16214d8_key -iv $encrypted_89b7d16214d8_iv -in deploy_key.enc -out deploy_key -d
  - npm install -g gulp
  - npm install -g bower
script: bash deploy.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "brycebedwell@gmail.com"
branches:
  only:
  - master